//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCoffeeABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDanhMucSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDanhMucSP()
        {
            this.tAnhSPs = new HashSet<tAnhSP>();
            this.tChiTietHDBs = new HashSet<tChiTietHDB>();
            this.tKichThuocs = new HashSet<tKichThuoc>();
            this.tNguyenLieuSPs = new HashSet<tNguyenLieuSP>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaHangSX { get; set; }
        public string GioiThieuSP { get; set; }
        public string MaLoai { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAnhSP> tAnhSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHDB> tChiTietHDBs { get; set; }
        public virtual tHangSX tHangSX { get; set; }
        public virtual tLoaiSP tLoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tKichThuoc> tKichThuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNguyenLieuSP> tNguyenLieuSPs { get; set; }
    }
}
