//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCoffeeABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNguyenLieu()
        {
            this.tNguyenLieuSPs = new HashSet<tNguyenLieuSP>();
        }
    
        public string MaNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public Nullable<decimal> ConLai { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
        public string DonViTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNguyenLieuSP> tNguyenLieuSPs { get; set; }
    }
}
